# NTP
- name: Install NTP package
  yum:
    name: chrony
    state: latest

- name: Edit chrony.conf file
  lineinfile:
    dest: /etc/chrony.conf
    regexp: "server NTP_SERVER iburst"
    line: "server 192.168.56.115 iburst"

- name: Chrony Daemon
  lineinfile:
    dest: /etc/chrony.conf
    line: "allow 10.0.0.0/24"
    backup: yes

- name: NTP Starting / Enabling
  service:
    name: chrony
    state: started
    enabled: yes

# OpenStack packages
- name: Install subscription manager
  yum:
    name: subscription-manager
    state: present

- name: Enable repositories (openstack)
  command: "subscription-manager repos --enable=rhel-7-server-optional-rpms --enable=rhel-7-server-extras-rpms --enable=rhel-7-server-rh-common-rpms"

- name: Add RDO repository
  apt_repository:
    url: https://rdoproject.org/repos/rdo-release.rpm
    state: present

- name: Install OpenStack Client
  yum:
    name: python-openstackclient

# SQL Database
- name: Install SQL packages
  yum:
    name:
      - mariadb
      - mariadb-server
      - python2-PyMySQL

- name: Create file (SQL)
  file:
    dest: /etc/my.cnf.d/openstack.cnf
    state: touch

- name: Edit file (SQL)
  lineinfile:
    path: /etc/my.cnf.d/openstack.cnf
    state: present
    line: "{{ item }}"
  with_items:
  - [mysqld]
  - bind-address = 10.0.0.11
  - |
  - default-storage-engine = innodb
  - innodb_file_per_table = on
  - max_connections = 4096
  - collation-server = utf8_general_ci
  - character-set-server = utf8

- name: Mariadb Restarting / Enabling
  service:
    name: mariadb.service
    state: start
    enabled: true

# Message Queue
- name: Install Message Queue package
  yum:
    name: rabbitmq-server
    state: latest

- name: Rabbitmq-server Starting / Enabling
  service:
    name: rabbitmq-server
    state: started
    enabled: true

- name: Add RabbitMQ user
  command: rabbitmqctl add_user openstack pacinos_tip

- name: Permit configuration
  command: rabbitmqctl set_permissions openstack ".*" ".*" ".*"

# memcached
- name: Install memcached packages
  yum:
    name:
      - memcached
      - python-memcache
    state: latest

- name: Edit file (memcached)
  lineinfile:
    path: /etc/sysconfig/memcached
    regexp: 'OPTIONS="-1 127.0.0.1,::1"'
    line: 'OPTIONS="-1 127.0.0.1,::1,controller"'

- name: memcached Starting / Enabling
  service:
    name: memcached
    state: start
    enabled: true

# Etcd
- name: Install Etcd package
  yum:
    name: etcd
    state: latest

- name: Edit file (Etcd)
  lineinfile:
    dest: /etc/default/etcd
    state: present
    line: "{{ item }}"
  loop:
  - {regexp: "ETCD_INITIAL_CLUSTER",
     line: 'ETCD_INITIAL_CLUSTER="controller=http://10.0.0.11:2380"'}
  - {regexp: "ETCD_INITIAL_ADVERTISE_PEER_URLS",
     line: 'ETCD_INITIAL_ADVERTISE_PEER_URLS="http://10.0.0.11:2380"'}
  - {regexp: "ETCD_ADVERTISE_CLIENT_URLS",
     line: 'ETCD_ADVERTISE_CLIENT_URLS="http://10.0.0.11:2379"'}
  - {regexp: "ETCD_LISTEN_CLIENT_URLS",
     line: 'ETCD_LISTEN_CLIENT_URLS="http://10.0.0.11:2379"'}

- name: Etcd Starting / Enabling
  service:
    name: etcd
    state: start
    enabled: true
